### ISSUE TITLE
Extremely inefficient Tree refresh

### ISSUE THREAD

**Issue by bogool** [SitePen/dgrid#1304]
It happens when the tree is expanded and it has many children.
Here is a working example of tree dgrid with one top item and 5000 children, and flat grid with 5001 rows

https://jsfiddle.net/bogool/qurcvjL4/
You can change balance between number of top level rows and children by changing these constants:

```javascript
    const top = 1;
    const children = 5000;
```
When you flip these values, performance will be better, but still tree renders much longer than flat grid.

A few examples of difference between refreshing tree grid and the flat grid with same number of rows on my computer:

Flat (s)|Tree (s)
----|----
0,015|15,02
0,023|15,61
0,045|15,66

I think this is because dgrid always renders all rows (5000 in this case) at children's level.

Maybe I'm doing something wrong?
In my project, I have several levels in tree with many children, and I can't collapse it to improve performance.

The second issue (but I think it is actually duplicate of #403): the keepScrollPosition doesn't work on the expanded tree.
This is really annoying for my users.

**Comment by bogool** [comment]
One more thing.
In Firefox refreshing the tree seems to be faster (~4,5s). Times in table above are obtained in Chrome.

**Comment by edhager** [comment]
We are working on a fix for issue #877 that will help will the performance of expanded rows.  Child rows will respond to changes in scroll position in the same way the top level rows do.

**Comment by bogool** [comment]
Thanks Ed!

**Comment by edhager** [comment]
@bogool, we pushed a commit to master (3cd8120b4a59932cddb2dbf1f2b649585e5d2b67) that prunes child rows the same way parent rows are pruned.  Give it a try.

**Comment by bogool** [comment]
@edhager , thanks for that.
Refresh is working faster now, but I found some other problems:

1. When you refresh the grid, it renders only 25 first rows.
2. When you scroll to about 200-250th row, Chrome tab hangs up for a while, and then crashes. Firefox tells "Too much recursion" on the console.

Because of 1. I don't know if keepScrollPosition is working properly.

Updated fiddle:
https://jsfiddle.net/bogool/qurcvjL4/4/

**Comment by edhager** [comment]
Thanks, I will take a look this week.

**Comment by edhager** [comment]
@bogool, give the code in master a try (2ae74378bff7ef0c46d82732a52e5f5cc55666ed).

There was a problem with how the grid's rowHeight property was being calculated.  Since your grid only had one parent row and when expanded, that row was really tall, rowHeight was calculated to be a large value.  For issue 1 above, the code thought the child rows were equally large which is why it determined that only 25 rows needed to be rendered.  Issue 2 above is actually the same issue described in ticket #1281.  

rowHeight is now being calculated at each level in the tree so the large expanded parent row has no effect on the calculated rowHeight for the child rows.  That solves both of your issues above.  I didn't fix the problem described in #1281.  You can still manually set the grid's rowHeight property to a large value and trigger the recursion problem.  #1281 will need its own solution.

keepScrollPosition hasn't worked for a while, maybe forever, with expanded tree rows.  I fixed that as well.

**Comment by edhager** [comment]
I fixed keepScrollPosition for your test case but I just created a more complicated scenario with the Rest.html page and I can cause refresh to break the tree.  So, it still needs work...

**Comment by bogool** [comment]
@edhager, after some quick tests I figured out that unfortunately there are still issues with the tree grid.

### Scenario 1 - 1 top row and 5000 children:

In Firefox it still doesn't work - only 25 rows are rendered, sometimes even before any refresh operation.

In Chrome it is working almost fine, but if you scroll to the last row (0.4999 in this case), and if you scroll back, then previous rows don't render until the row ~0.3300. Then rows render properly again.

### Scenario 2 - Tree is more balanced, e.g. 100 top entries, 100 children each

At first, before refresh, scrolling seems to be ok, but if you scroll to row ~250 (1.50) and then a quick return to row 0, one of these situations happens:

1. the grid renders only 24 children for each top level row, or
2. after the top level row, the grid leaves blank space for some rows, and then renders 75-99th or 37-99th children, or
3. the grid renders only 37-99th or 75-99th children right after each top level row, or
4. the grid renders 0-72nd children and then leaves a blank space, or
5. some combination of the above for each top level row

Further scrolling, regardless of which direction, results in one of the above situations, some mix of them or/and sometimes is quite unpredictable - rows with greater numbers are rendered before rows with lower numbers.

After refreshing, Chrome behaves like above, but it renders only 25 top level rows. Firefox genrally renders only 25 top level rows with 24 children per each top level row, but sometimes acts like above as well.

btw. Both browsers writes errors on the console:
`Tree.js:273 Uncaught TypeError: Cannot read property 'previous' of undefined` - Chrome
`TypeError: preload is undefined Tree.js:273:7` - Firefox


The behavior of the tree, even in this simple case, is generally unpredictable. In the same conditions, it seems to behave differently.

If you need some more accurate tests, I can try to do them for you.

**Comment by bogool** [comment]
Hi @edhager,
Any progress on this issue?
